# 3.1. Rounding Numerical Values

In [8]:
# round(value, ndigits) function
round(1.23,1)
round(1.27,1)

# When a value is exactly halfway between two choices, the behavior of round is to round to the nearest even digit
round(1.5,0)
round(3.5,0)
round(1627731,-1) # negative rounding takes place for tens, hundreds, thousands

1627730

# 3.2. Performing Accurate Decimal Calculations


In [16]:
# A well-known issue with floating-point numbers is that they can't accurately represent all base-10 decimals 
a = 4.2
b = 2.1
a+b
(a + b) == 6.3
from decimal import Decimal
a = Decimal('4.2')
b = Decimal('2.1')
( a + b ) == Decimal('6.3')
from decimal import localcontext
a = Decimal('1.3')
b = Decimal('1.7')
print(a / b)
with localcontext() as ctx:
    ctx.prec = 3 
    print(a/b)

with localcontext() as ctx:
    ctx.prec = 100
    print(a/b)

0.7647058823529411764705882353
0.765
0.7647058823529411764705882352941176470588235294117647058823529411764705882352941176470588235294117647


# 3.3. Formatting Numbers for Output

In [9]:
# To format a single number for output
x = 1234.5678

# Two decimal places of accuracy 
format(x, '0.2f')

# Right justfied in 10 chars, one-digit accuracy 
format(x, '>10.1f')

# Left justfied 
format(x, '<10.1f')

# Centered 
format(x, '^10.1f')

# Inclusion of thousands separator 
format(x, ',')
format(x, ',.1f')

# use exponential notation 
format(x, 'e')
format(x, '0.2E')

'1.23E+03'

# 3.4. Working with Binary,Octal,and Hexadecimal Integers

In [21]:
# To convert an integer into a binary, octal, or hexadecimal text string, use the bin(), oct(), or hex() function 
x = 1234
bin(x)
oct(x)
hex(x)

# use the format() function if you don't want the 0b, 0o, 0x prefixes to appear
format(x, 'b')
format(x,'o')
format(x,'x')

# To convert integer strings in different bases, simply use the int() function with an appropriate base
int('4d2',16)
int('10011010010',2)

# The Python syntax for specifying octal values is slightly different than many other languages 
import os 
#os.chmod('abc.py',0o775)

# 3.5.Packing and Unpacking Large Integers from Bytes

In [29]:
data = b'\x00\x124V\x00x\x90\xab\x00\xcd\xef\x01\x00#\x004'
len(data)
# To interpret the bytes as an integer, use int.from_bytes()
int.from_bytes(data, 'little')
int.from_bytes(data, 'big')

# To large integer value back into a byte string, use the int.to_bytes() method 
x = 94522842520747284487117727783387188
x.to_bytes(16, 'big')
x.to_bytes(16, 'little')

data = x.to_bytes(16, 'big')
import struct 
hi, lo = struct.unpack('>QQ', data)
(hi << 64) + lo

94522842520747284487117727783387188

# 3.6. Performing Complex-Valued Math

In [42]:
# Complex numbers can be specified using the complex(real, imag) function or by floating-point numbers with a j suffix 
a = complex(2,4)
b = 3 - 5j 
print(a,b)
print(a.real, b.real)
print(a.imag, b.imag)
print(a.conjugate(), b.conjugate())
print(a+b, a-b, a*b, a/b, abs(a), abs(b))

import cmath # cmath declare the use of a complex type in libraries
print(cmath.sin(a), cmath.cos(a), cmath.exp(a))

import numpy as np 
a = np.array([2+3j, 4+5j, 6-7j, 8+9j])
a + 2
np.sin(a)

# Python standard mathematical functions do not produce complex values by default

(2+4j) (3-5j)
2.0 3.0
4.0 -5.0
(2-4j) (3+5j)
(5-1j) (-1+9j) (26+2j) (-0.4117647058823529+0.6470588235294118j) 4.47213595499958 5.830951894845301
(24.83130584894638-11.356612711218173j) (-11.36423470640106-24.814651485634183j) (-4.829809383269385-5.5920560936409816j)


array([   9.15449915  -4.16890696j,  -56.16227422 -48.50245524j,
       -153.20827755-526.47684926j, 4008.42651446-589.49948373j])

# 3.7. Working with Infinity and NaNs

In [58]:
import math 

a = float('inf')
b = float('-inf')
c = float('nan')
print(a,b,c)
# To test for the presence of these values 
math.isinf(a)
math.isnan(c)

# Infinite value 无穷
a = float('inf') + 45
10/a
a = float('inf')
a/a
b = float('-inf')
a+b

# NaN values propagate through all operations without raising an exception 
c = float('nan')
c + 23
c/2
c*2
math.sqrt(c)

# NaN values is that they never compare as equal 
c = float('nan')
d = float('nan')
c == d
math.isnan(np.nan)

inf -inf nan


True

# 3.8. Calculating with Fractions(分数)

In [67]:
from fractions import Fraction 
a = Fraction(5,4)
b = Fraction(7,16)
print(a+b)
print(a*b)

# Getting numerator/denominator 
c = a * b
c.numerator
c.denominator

# Converting to a float
float(c)

# Limiting the denominator of a value 
print(c.limit_denominator(8))

# Converting a float to a fraction 
x = 3.75 
y = Fraction(*x.as_integer_ratio())
y

27/16
35/64
4/7


Fraction(15, 4)

# 3.9. Calculating with Large Numerical Arrays

In [90]:
# The NumPy library. The major feature of NumPy is that it gives Python an array object that is much more efficient and better suited for mathematical calculation than a standard Python List
# Python lists 
x = [1,2,3,4]
y = [5,6,7,8]
x * 2
#x + 10
x + y

# Numpy arrays 
import numpy as np 
ax = np.array([1,2,3,4])
ay = np.array([5,6,7,8])
ax * 2
ax + 10
ax+ay
ax*ay

np.sqrt(ax)
np.cos(ax)

grid = np.zeros(shape=(10000, 10000), dtype=float)
grid += 10
#np.sin(grid)

a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)

# Select row 1
a[1]

# Select column 1 
a[:,1]

# Select a subregion and change it 
a[1:3, 1:3] += 10 

# Broadcast a row vector across an operation on all rows
print(a + [100, 101, 102, 103])

# Confitional assignment on an array 
np.where(a < 10, a, 10)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[101 103 105 107]
 [105 117 119 111]
 [109 121 123 115]]


array([[ 1,  2,  3,  4],
       [ 5, 10, 10,  8],
       [ 9, 10, 10, 10]])

# 3.10. Performing Matrix and Linear Algebra Calculations

In [97]:
import numpy as np 
m = np.matrix([[1,-2,3],[0,4,5],[7,8,-9]])

# Return transpose 
m.T

# Return inverse 
m.I 

# Create a vector and multiply 
v = np.matrix([[2],[3],[4]])
m * v 

matrix([[ 8],
        [32],
        [ 2]])

# 3.11. Picking Things at Random

In [134]:
# The random module has various functions for random numbers and picking random items
import random 
values = [1, 2, 3, 4, 5, 6]
random.choice(values)

# To take a sampling of N items where selected items are removed from further consideration 
random.sample(values, 2)
random.sample(values, 2)

# shuffle items in a sequence in place 
random.shuffle(values)

# Produce random integers, use random.randint()
random.randint(0, 10)

# Produce uniform floating-point values in the range 0 to 1, use random.random()
random.random()

# get N random-bits expressed as an integer 
print(random.getrandbits(100))

# Random module computes random numbers using the Mersenne Twister algorithm
random.seed() # Seed based on system time or os.urandom() 
random.seed(12345) # Seed based on integer given 
random.seed(b'bytedata') # Seed based on byte data 

# random() includes functions for uniform, Gaussian, and other probabality distributions 
#random.uniform() # computes uniformly
#random.gauss() # gauss 

183791128314085330743114982343


# 3.12. Converting Days to Seconds, and Other Basic Time Conversions

In [154]:
from datetime import timedelta
a = timedelta(days=2, hours=6)
b = timedelta(hours=4.5)
c = a + b
c.days
c.seconds
c.total_seconds() / 3600

# Represent specific dates and times, create datetime instance 
from datetime import datetime 
a = datetime(2012, 9, 23)
print(a + timedelta(days=10))
b = datetime(2012, 12, 21)
d = b-a
d.days
now = datetime.today()
print(now)
print(now + timedelta(minutes=10))

# noted that datetime is aware of leap years 
a = datetime(2012, 3, 1)
b = datetime(2012, 2, 28)
(a-b).days

c = datetime(2013, 3, 1)
d = datetime(2013, 2, 28)
(c-d).days

a = datetime(2012, 9, 23)
from dateutil.relativedelta import relativedelta
a + relativedelta(months=+1)
a + relativedelta(months=+4)

# Time between two dates
b = datetime(2012, 12, 21)
d = b - a
d = relativedelta(b,a)
d.months

2012-10-03 00:00:00
2018-01-24 18:02:25.935459
2018-01-24 18:12:25.935459


2

# 3.13. Determining Last Friday's Date

In [163]:
from datetime import datetime, timedelta 

weekdays = ['Monday', 'Tuesday', 'Wednesday', 'Thurday', 'Friday', 'Saturday', 'Sunday']

def get_previous_byday(dayname, start_date=None):
    if start_date is None:
        start_date = datetime.today() 
    day_num = start_date.weekday()
    day_num_target = weekdays.index(dayname)
    days_ago = (7 + day_num - day_num_target) % 7
    if days_ago == 0:
        days_ago = 7
    target_date = start_date - timedelta(days=days_ago)
    return target_date

datetime.today() # For reference 
get_previous_byday('Monday')
get_previous_byday('Wednesday')
get_previous_byday('Sunday', datetime(2012, 12, 21))

from datetime import datetime 
from dateutil.relativedelta import relativedelta 
from dateutil.rrule import * 

d = datetime.now()
print(d)

# Next Friday 
print(d + relativedelta(weekday=FR))

# Last Friday 
print(d + relativedelta(weekday=FR(-1)))

2018-01-24 18:18:46.870022
2018-01-26 18:18:46.870022
2018-01-19 18:18:46.870022


# 3.14. Finding the Date Range for the Current Month

In [167]:
from datetime import datetime, date, timedelta 
import calendar 

def get_month_range(start_date=None):
    if start_date is None:
        start_date = date.today().replace(day=1)
    _, days_in_month = calendar.monthrange(start_date.year, start_date.month) # find out how many days are inthe month in question
    end_date = start_date + timedelta(days=days_in_month)
    return (start_date, end_date)

a_day = timedelta(days=1)
first_day, last_day = get_month_range()

while first_day < last_day:
    print(first_day)
    first_day += a_day

def date_range(start, stop, step):
    while start < stop:
        yield start 
        start += step 

for d in date_range(datetime(2012, 9, 1), datetime(2012, 10, 1), timedelta(hours=6)):
    print(d)

2018-01-01
2018-01-02
2018-01-03
2018-01-04
2018-01-05
2018-01-06
2018-01-07
2018-01-08
2018-01-09
2018-01-10
2018-01-11
2018-01-12
2018-01-13
2018-01-14
2018-01-15
2018-01-16
2018-01-17
2018-01-18
2018-01-19
2018-01-20
2018-01-21
2018-01-22
2018-01-23
2018-01-24
2018-01-25
2018-01-26
2018-01-27
2018-01-28
2018-01-29
2018-01-30
2018-01-31
2012-09-01 00:00:00
2012-09-01 06:00:00
2012-09-01 12:00:00
2012-09-01 18:00:00
2012-09-02 00:00:00
2012-09-02 06:00:00
2012-09-02 12:00:00
2012-09-02 18:00:00
2012-09-03 00:00:00
2012-09-03 06:00:00
2012-09-03 12:00:00
2012-09-03 18:00:00
2012-09-04 00:00:00
2012-09-04 06:00:00
2012-09-04 12:00:00
2012-09-04 18:00:00
2012-09-05 00:00:00
2012-09-05 06:00:00
2012-09-05 12:00:00
2012-09-05 18:00:00
2012-09-06 00:00:00
2012-09-06 06:00:00
2012-09-06 12:00:00
2012-09-06 18:00:00
2012-09-07 00:00:00
2012-09-07 06:00:00
2012-09-07 12:00:00
2012-09-07 18:00:00
2012-09-08 00:00:00
2012-09-08 06:00:00
2012-09-08 12:00:00
2012-09-08 18:00:00
2012-09-09 00:00:00

# 3.15. Converting Strings into Datetimes

In [174]:
from datetime import datetime
text = '2012-09-20'
# striptime written in pure Python 
y = datetime.strptime(text, '%Y-%m-%d')
z = datetime.now()
diff = z - y
diff
z
nice_z = datetime.strftime(z, '%A %B %d, %Y')
nice_z

from datetime import datetime

def parse_ymd(s):
    year_s, mon_s, day_s = s.split('-')
    return datetime(int(year_s), int(mon_s), int(day_s))

# 3.16. Manipulating Dates Involving Time Zones

In [188]:
# involving time zones, you should use the pytz module
# provides the Olson time zone database 
from datetime import datetime 
from pytz import timezone 

d = datetime(2012, 12, 21, 9, 30, 0)
print(d)

# Localize the date for Chicago
central = timezone('US/Central')
loc_d = central.localize(d)
print(loc_d)

# Convert to Bangalore time 
bang_d = loc_d.astimezone(timezone('Asia/Kolkata'))
print(bang_d)

d = datetime(2013, 3, 10, 1, 45)
loc_d = central.localize(d)
print(loc_d)

later = loc_d + timedelta(minutes=30)
print(later)

from datetime import timedelta
later = central.normalize(loc_d + timedelta(minutes=30))
print(later)

import pytz 
# convert all dates to UTC time 
utc_d = loc_d.astimezone(pytz.utc)
print(utc_d)

later_utc = utc_d + timedelta(minutes=30)
print(later_utc.astimezone(central))

pytz.country_timezones['CN'] # 'Asia/Shanghai', 'Asia/Urumqi'乌鲁木齐

2012-12-21 09:30:00
2012-12-21 09:30:00-06:00
2012-12-21 21:00:00+05:30
2013-03-10 01:45:00-06:00
2013-03-10 02:15:00-06:00
2013-03-10 03:15:00-05:00
2013-03-10 07:45:00+00:00
2013-03-10 03:15:00-05:00


['Asia/Shanghai', 'Asia/Urumqi']